# Spanish message translation file for plpython
# Copyright (C) 2009 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Emanuel Calvo Franco <postgres.arg@gmail.com>, 2009.
# Alvaro Herrera <alvherre@alvh.no-ip.org>, 2009
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 8.4\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2009-04-11 19:22+0000\n"
"PO-Revision-Date: 2009-04-11 16:28-0400\n"
"Last-Translator: Emanuel Calvo Franco <postgres.arg@gmail.com>\n"
"Language-Team: PgSQL-es-Ayuda <pgsql-es-ayuda@postgresql.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;"

#: plpython.c:420 plpython.c:445
msgid "unexpected return value from trigger procedure"
msgstr "valor de retorno no esperado desde el procedimiento disparador"

#: plpython.c:421
msgid "Expected None or a string."
msgstr "Se esperaba None o una cadena."

#: plpython.c:435
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"función de disparador de PL/Python retorno «MODIFY» en un disparador de tipo "
"DELETE -- ignorado"

#: plpython.c:446
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Se esperaba None, «OK», «SKIP» o «MODIFY»."

#: plpython.c:493
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] borrado, no se puede modicar el registro"

#: plpython.c:496
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] no es un diccionario"

#: plpython.c:515
#, c-format
msgid "name of TD[\"new\"] attribute at ordinal position %d is not a string"
msgstr ""
"el nombre del atributo de TD[\"new\"] en la posición %d no es una cadena"

#: plpython.c:519
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"la llave «%s» en TD[\"new\"] no existe como columna en la "
"fila disparadora"

#: plpython.c:540
#, c-format
msgid ""
"could not compute string representation of Python object in PL/Python "
"function \"%s\" while modifying trigger row"
msgstr ""
"no se pudo calcular la representación de la cadena del objeto Python en "
"la función de PL/Python «%s» mientras se modificaba la fila del disparador"

#: plpython.c:622
msgid "could not create new dictionary while building trigger arguments"
msgstr ""
"no se pudo crear un nuevo diccionario mientras se construían los argumentos "
"de disparador"

#: plpython.c:830
msgid "unsupported set function return mode"
msgstr "modo de retorno de conjunto de función no soportado"

#: plpython.c:831
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""
"Las funciones PL/Python que retornan conjuntos sólo permiten retornar un valor por invocación."

#: plpython.c:843
msgid "returned object cannot be iterated"
msgstr "objeto retornado no puede ser iterado"

#: plpython.c:844
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"Los funciones PL/Python que retornan conjuntos deben retornar un objeto iterable."

#: plpython.c:872
msgid "error fetching next item from iterator"
msgstr "error extrayendo el próximo elemento del iterador"

#: plpython.c:890
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "función PL/Python con tipo de retorno «void» no retorna None"

#: plpython.c:937
#, c-format
msgid ""
"could not create string representation of Python object in PL/Python "
"function \"%s\" while creating return value"
msgstr ""
"no se pudo crear la representación de cadena del objeto Python en la "
"función PL/Python «%s» mientras creaba el valor de retorno"

#: plpython.c:986
#, c-format
msgid "PL/Python function \"%s\" failed"
msgstr "la función PL/Python «%s» ha fallado"

#: plpython.c:1056
#, c-format
msgid ""
"PyList_SetItem() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""
"PyDict_SetItem() falló para la función PL/Python «%s» mientras se "
"inicializaban los argumentos"

#: plpython.c:1060
#, c-format
msgid ""
"PyDict_SetItemString() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""
"PyDict_SetItemString() falló para la función PL/Python «%s» mientras se "
"inicializaban los argumentos"

#: plpython.c:1238
msgid "trigger functions can only be called as triggers"
msgstr "las funciones disparadoras sólo pueden ser llamadas como disparadores"

#: plpython.c:1242
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "las funciones PL/Python no pueden retornar el tipo %s"

#: plpython.c:1321
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "la funciones PL/Python no pueden aceptar el tipo %s"

#: plpython.c:1415
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "no se pudo compilar la función PL/Python «%s»"

#: plpython.c:1727
msgid "could not create new dictionary"
msgstr "no se pudo crear un nuevo diccionario"

#: plpython.c:1814 plpython.c:1903 plpython.c:1974
msgid "could not compute string representation of Python object"
msgstr "no se pudo calcular la representación de cadema del objeto de Python"

#: plpython.c:1828
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la llave «%s» no fue encontrada en el mapa"

#: plpython.c:1829
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"Para retornar null en una columna, agregue el valor None al mapa, con llave "
"llamada igual que la columna."

#: plpython.c:1873
msgid "length of returned sequence did not match number of columns in row"
msgstr ""
"el tamaño de la secuencia retornada no concuerda con el número de columnas de "
"la fila"

#: plpython.c:1987
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "el atributo «%s» no existe en el objeto Python"

#: plpython.c:1988
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"Para retornar null en una columna, haga que el objeto retornado tenga un "
"atributo llamado igual que la columna, con valor None."

#: plpython.c:2210
msgid "plan.status takes no arguments"
msgstr "plan.status no lleva argumentos"

#: plpython.c:2340 plpython.c:2479
msgid "transaction aborted"
msgstr "transacción abortada"

#: plpython.c:2347
msgid "invalid arguments for plpy.prepare"
msgstr "argumentos no válidos para plpy.prepare"

#: plpython.c:2354
msgid "second argument of plpy.prepare must be a sequence"
msgstr "el segundo argumento de plpy.prepare debe ser una secuencia"

#: plpython.c:2399
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr ""
"plpy.prepare: el nombre de tipo en la posición %d no es una cadena"

#: plpython.c:2426
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare no soporta tipos compuestos"

#: plpython.c:2454
msgid "unrecognized error in PLy_spi_prepare"
msgstr "error no reconocido en PLy_spi_prepare"

#: plpython.c:2456 plpython.c:2618 plpython.c:2665
#, c-format
msgid "in PL/Python function \"%s\""
msgstr "en función PL/Python «%s»"

#: plpython.c:2492
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute espera una consulta o un plan"

#: plpython.c:2509
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute lleva una secuencia como segundo argumento"

#: plpython.c:2525 plpython.c:2552
#, c-format
msgid "PL/Python function \"%s\" could not execute plan"
msgstr "la función PL/Python «%s» no pudo ejecutar el plan"

#: plpython.c:2529
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Se esperaba una secuencia de %d argumento, se obtuvo %d: %s"
msgstr[1] "Se esperaba una secuencia de %d argumentos, se obtuvo %d: %s"

#: plpython.c:2616
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr "error no reconocido en PLy_spi_execute_plan"

#: plpython.c:2637
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "falló SPI_execute_plan: %s"

#: plpython.c:2663
msgid "unrecognized error in PLy_spi_execute_query"
msgstr "error no reconocido en PLy_spi_execute_query"

#: plpython.c:2674
#, c-format
msgid "SPI_execute failed: %s"
msgstr "falló SPI_execute: %s"

#: plpython.c:2734
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "error desconocido en PLy_spi_execute_fetch_result"

#: plpython.c:2770
msgid "untrapped error in initialization"
msgstr "error no capturado en la inicialización"

#: plpython.c:2773
msgid "could not create procedure cache"
msgstr "no se pudo crear el cache de procedimientos"

#: plpython.c:2785
msgid "could not import \"__main__\" module"
msgstr "no se pudo importar el módulo «__main__»"

#: plpython.c:2792
msgid "could not initialize globals"
msgstr "no se pudo inicializar las globales"

#: plpython.c:2894
msgid "could not parse error message in plpy.elog"
msgstr "no se pudo analizar el mensaje de error de plpy.elog"

#: plpython.c:2990
#, c-format
msgid "PL/Python: %s"
msgstr "PL/Python: %s"

#: plpython.c:2991
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3081
msgid "out of memory"
msgstr "memoria agotada"
