# Brazilian Portuguese message translation file for plpython
# Copyright (C) 2009 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Euler Taveira de Oliveira <euler@timbira.com>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 8.4\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2009-05-06 18:00-0300\n"
"PO-Revision-Date: 2009-05-10 01:15-0300\n"
"Last-Translator: Euler Taveira de Oliveira <euler@timbira.com>\n"
"Language-Team: Brazilian Portuguese <pgbr-dev@listas.postgresql.org.br>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n>1);\n"

#: plpython.c:420 plpython.c:445
msgid "unexpected return value from trigger procedure"
msgstr "função de gatilho retornou valor inesperado"

#: plpython.c:421
msgid "Expected None or a string."
msgstr "None ou uma cadeia de caracteres era esperado."

#: plpython.c:435
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"função de gatilho PL/Python retornou \"MODIFY\" em um gatilho DELETE -- ignorado"

#: plpython.c:446
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Era esperado None, \"OK\", \"SKIP\" ou \"MODIFY\"."

#: plpython.c:493
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] removido, não pode modificar registro"

#: plpython.c:496
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] não é um dicionário"

#: plpython.c:515
#, c-format
msgid "name of TD[\"new\"] attribute at ordinal position %d is not a string"
msgstr "nome do atributo TD[\"new\"] na posição %d não é uma cadeia de caracteres"

#: plpython.c:519
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"chave \"%s\" encontrada em TD[\"new\"] não existe como uma coluna no registro do gatilho"

#: plpython.c:540
#, c-format
msgid ""
"could not compute string representation of Python object in PL/Python "
"function \"%s\" while modifying trigger row"
msgstr ""
"não pode produzir representação em cadeia de caracteres do objeto Python na função \"%s\" ao modificar registro do gatilho"

#: plpython.c:622
msgid "could not create new dictionary while building trigger arguments"
msgstr "não pode criar novo dicionário ao construir argumentos do gatilho"

#: plpython.c:830
msgid "unsupported set function return mode"
msgstr "modo de retorno da função que retorna conjunto não é suportado"

#: plpython.c:831
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""
"funções PL/Python que retornam conjunto só suportam retornar um valor por chamada."

#: plpython.c:843
msgid "returned object cannot be iterated"
msgstr ""

#: plpython.c:844
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""

#: plpython.c:872
msgid "error fetching next item from iterator"
msgstr ""

#: plpython.c:890
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "função PL/Python com tipo de retorno \"void\" não retornou None"

#: plpython.c:937
#, c-format
msgid ""
"could not create string representation of Python object in PL/Python "
"function \"%s\" while creating return value"
msgstr ""
"não pode produzir representação em cadeia de caracteres do objeto Python na função \"%s\" ao criar valor de retorno"

#: plpython.c:986
#, c-format
msgid "PL/Python function \"%s\" failed"
msgstr "função PL/Python \"%s\" falhou"

#: plpython.c:1056
#, c-format
msgid ""
"PyList_SetItem() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""
"PyList_SetItem() falhou para função PL/Python \"%s\" ao definir argumentos"

#: plpython.c:1060
#, c-format
msgid ""
"PyDict_SetItemString() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""
"PyDict_SetItemString() falhou para função PL/Python \"%s\" ao definir argumentos"

#: plpython.c:1238
msgid "trigger functions can only be called as triggers"
msgstr "funções de gatilho só podem ser chamadas como gatilhos"

#: plpython.c:1242
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "funções PL/Python não podem retornar tipo %s"

#: plpython.c:1321
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "funções PL/Python não podem aceitar tipo %s"

#: plpython.c:1415
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "não pôde compilar função PL/Python \"%s\""

#: plpython.c:1727
msgid "could not create new dictionary"
msgstr "não pôde criar novo dicionário"

#: plpython.c:1814 plpython.c:1903 plpython.c:1974
msgid "could not compute string representation of Python object"
msgstr "não pôde computar representação de uma cadeia de caracteres de um objeto Python"

#: plpython.c:1828
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "chave \"%s\" não foi encontrada no mapeamento"

#: plpython.c:1829
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""

#: plpython.c:1873
msgid "length of returned sequence did not match number of columns in row"
msgstr "tamanho da sequência retornada não combina com número de colunas no registro"

#: plpython.c:1987
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "atributo \"%s\" não existe no objeto Python"

#: plpython.c:1988
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""

#: plpython.c:2210
msgid "plan.status takes no arguments"
msgstr "plan.status não contém argumentos"

#: plpython.c:2340 plpython.c:2479
msgid "transaction aborted"
msgstr "transação interrompida"

#: plpython.c:2347
msgid "invalid arguments for plpy.prepare"
msgstr "argumentos inválidos para plpy.prepare"

#: plpython.c:2354
msgid "second argument of plpy.prepare must be a sequence"
msgstr "segundo argumento de plpy.prepare deve ser uma sequência"

#: plpython.c:2399
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: nome do tipo na posição %d não é uma cadeia de caracteres"

#: plpython.c:2426
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare não suporta tipos compostos"

#: plpython.c:2454
msgid "unrecognized error in PLy_spi_prepare"
msgstr "erro desconhecido em PLy_spi_prepare"

#: plpython.c:2456 plpython.c:2618 plpython.c:2665
#, c-format
msgid "in PL/Python function \"%s\""
msgstr "na função PL/Python \"%s\""

#: plpython.c:2492
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute espera uma consulta ou um plano"

#: plpython.c:2509
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute recebe uma sequência como segundo argumento"

#: plpython.c:2525 plpython.c:2552
#, c-format
msgid "PL/Python function \"%s\" could not execute plan"
msgstr "função PL/Python \"%s\" não pode executar o plano"

#: plpython.c:2529
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequência esperada de %d argumento, recebeu %d: %s"
msgstr[1] "Sequência esperada de %d argumentos, recebeu %d: %s"

#: plpython.c:2616
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr "erro desconhecido em PLy_spi_execute_plan"

#: plpython.c:2637
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan falhou: %s"

#: plpython.c:2663
msgid "unrecognized error in PLy_spi_execute_query"
msgstr "erro desconhecido em PLy_spi_execute_query"

#: plpython.c:2674
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute falhou: %s"

#: plpython.c:2734
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "erro desconhecido em PLy_spi_execute_fetch_result"

#: plpython.c:2770
msgid "untrapped error in initialization"
msgstr ""

#: plpython.c:2773
msgid "could not create procedure cache"
msgstr "não pôde criar cache da função"

#: plpython.c:2785
msgid "could not import \"__main__\" module"
msgstr "não pôde importar módulo \"__main__\""

#: plpython.c:2792
msgid "could not initialize globals"
msgstr ""

#: plpython.c:2894
msgid "could not parse error message in plpy.elog"
msgstr "não pode analisar mensagem de erro em plpy.elog"

#: plpython.c:2990
#, c-format
msgid "PL/Python: %s"
msgstr "PL/Python: %s"

#: plpython.c:2991
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3081
msgid "out of memory"
msgstr "sem memória"
